name: nyc_airbnb_dev
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.13
  - hydra-core
  - matplotlib
  - pandas
  - jupyterlab
  - pip
  - scipy
  - pytest
  - pip:
      - mlflow==3.1.4
      - wandb==0.22.0
